services:
  backend-flask-service:
    build: 
      context: ./backend-flask-service
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  
  frontend-nginx-service:
    build:
      context: ./frontend-nginx-service
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend-flask-service

      
  mongo-logs-service:
    build:
      context: ./mongo-logs-service
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - backend-flask-service
      - frontend-nginx-service
    environment:
      - MONGO_URI=mongodb://mongodb:27017/

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
